parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"CwIm":[function(require,module,exports) {
"use strict";var e,t,s;Object.defineProperty(exports,"__esModule",{value:!0}),exports.Message=exports.Cell=exports.GameState=void 0,exports.GameState=e,function(e){e[e.WaitingForPlayers=0]="WaitingForPlayers",e[e.Playing=1]="Playing",e[e.Finished=2]="Finished"}(e||(exports.GameState=e={})),exports.Cell=t,function(e){e[e.Empty=0]="Empty",e[e.X=1]="X",e[e.O=2]="O"}(t||(exports.Cell=t={})),exports.Message=s,function(e){e[e.PlayerSelection=0]="PlayerSelection",e[e.PlayerIndex=1]="PlayerIndex"}(s||(exports.Message=s={}));
},{}],"PAjV":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.TicTacToeState=void 0;var e=require("tslib"),t=require("@colyseus/schema"),r=require("../types/message");class a extends t.Schema{constructor(){super(),this.gameState=r.GameState.WaitingForPlayers,this.activePlayer=0,this.winningPlayer=-1,this.board=new t.ArraySchema(0,0,0,0,0,0,0,0,0)}}exports.TicTacToeState=a,(0,e.__decorate)([(0,t.type)("number")],a.prototype,"gameState",void 0),(0,e.__decorate)([(0,t.type)(["number"])],a.prototype,"board",void 0),(0,e.__decorate)([(0,t.type)("number")],a.prototype,"activePlayer",void 0),(0,e.__decorate)([(0,t.type)("number")],a.prototype,"winningPlayer",void 0);
},{"../types/message":"CwIm"}],"i2MV":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.NextTurnCommand=void 0;var e=require("@colyseus/command");class t extends e.Command{execute(){const e=this.room.state.activePlayer;this.room.state.activePlayer=0===e?1:0}}exports.NextTurnCommand=t;
},{}],"hnwH":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.CheckWinnerCommand=void 0;var o=require("@colyseus/command"),r=require("../../types/message"),e=require("./NextTurnCommand");const t=(o,r,e)=>{return o[3*r+e]},l=[[{row:0,col:0},{row:0,col:1},{row:0,col:2}],[{row:1,col:0},{row:1,col:1},{row:1,col:2}],[{row:2,col:0},{row:2,col:1},{row:2,col:2}],[{row:0,col:0},{row:1,col:0},{row:2,col:0}],[{row:0,col:1},{row:1,col:1},{row:2,col:1}],[{row:0,col:2},{row:1,col:2},{row:2,col:2}],[{row:0,col:0},{row:1,col:1},{row:2,col:2}],[{row:0,col:2},{row:1,col:1},{row:2,col:0}]];class c extends o.Command{determineWin(){for(let o=0;o<l.length;++o){let e=!0;const c=l[o];for(let o=1;o<c.length;++o){const l=c[o-1],n=c[o],s=t(this.state.board,l.row,l.col);if(s!==t(this.state.board,n.row,n.col)||s===r.Cell.Empty){e=!1;break}}if(e)return c}return!1}execute(){const o=this.determineWin();if(!o)return[new e.NextTurnCommand];console.log("win",o,this.state.board),this.state.winningPlayer=this.state.activePlayer}}exports.CheckWinnerCommand=c;
},{"../../types/message":"CwIm","./NextTurnCommand":"i2MV"}],"pUCL":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("@colyseus/command"),t=require("../../types/message"),r=require("./CheckWinnerCommand");class s extends e.Command{execute(e){const{client:s,index:n}=e;if(this.room.state.gameState!==t.GameState.Playing)return;const o=this.room.clients.findIndex(e=>e.id===s.id);if(o!==this.room.state.activePlayer)return;const i=0===o?t.Cell.X:t.Cell.O;return this.room.state.board[n]=i,[new r.CheckWinnerCommand]}}exports.default=s;
},{"../../types/message":"CwIm","./CheckWinnerCommand":"hnwH"}],"zEuH":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.TicTacToe=void 0;var e=require("colyseus"),t=require("@colyseus/command"),s=require("./TicTacToeState"),i=require("../types/message"),a=n(require("./commands/PlayerSelectionCommand"));function n(e){return e&&e.__esModule?e:{default:e}}const o=2;class r extends e.Room{constructor(){super(...arguments),this.dispatcher=new t.Dispatcher(this)}onCreate(){this.maxClients=o,this.setState(new s.TicTacToeState),this.onMessage(i.Message.PlayerSelection,(e,t)=>{this.dispatcher.dispatch(new a.default,{client:e,index:t.index})})}onJoin(e){const t=this.clients.findIndex(t=>t.sessionId===e.sessionId);e.send(i.Message.PlayerIndex,{playerIndex:t}),this.clients.length>=o&&(this.state.gameState=i.GameState.Playing,this.lock())}onLeave(e,t){this.state.winningPlayer=0===this.state.activePlayer?1:0}}exports.TicTacToe=r;
},{"./TicTacToeState":"PAjV","../types/message":"CwIm","./commands/PlayerSelectionCommand":"pUCL"}],"QCba":[function(require,module,exports) {
"use strict";var e=c(require("http")),r=c(require("express")),s=c(require("cors")),u=require("colyseus"),t=require("@colyseus/monitor"),o=require("./TicTacToe");function c(e){return e&&e.__esModule?e:{default:e}}const i=Number(process.env.PORT||2567),n=(0,r.default)();n.use((0,s.default)()),n.use(r.default.json());const a=e.default.createServer(n),l=new u.Server({server:a});l.define("tic-tac-toe",o.TicTacToe),n.use("/colyseus",(0,t.monitor)()),l.listen(i);
},{"./TicTacToe":"zEuH"}]},{},["QCba"], null)